#!/usr/bin/env lua
package.path = package.path .. ";./?.lua;./?/init.lua"
-- print("Package path: " .. package.path)
-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
