#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	external_bar main:23:0 \
	menubar_opacity 0.8 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.0 \
	window_opacity_duration 0.0 \
	active_window_opacity 0.95 \
	normal_window_opacity 0.75 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 3 \
	bottom_padding 3 \
	left_padding 3 \
	right_padding 3 \
	window_gap 3 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

yabai -m rule --add app="^(Logi Options Plus|Karabiner-Elements|Calculator|Software Update|Dictionary|System Preferences|System Settings|Archive Utility|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

echo "yabai configuration loaded.."
