return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "beautysh",
        "checkstyle",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint_d",
        "flake8",
        "goimports-reviser",
        "golangci-lint",
        "golines",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "prettier",
        "shellcheck",
        "shfmt",
        "sonarlint-language-server",
        "stylua",
        "tailwindcss-language-server",
        "typescript-language-server",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
