#!/bin/bash

options=(
	style=round
	width=3.0
	hidpi=off
	active_color=0xff89dceb
	# active_color=0xffe1e3e4
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
	# 	blur_radius=25
)

borders "${options[@]}"
